# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\generator.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnNext_Background = QtWidgets.QPushButton(self.centralwidget)
        self.btnNext_Background.setGeometry(QtCore.QRect(120, 650, 111, 23))
        self.btnNext_Background.setObjectName("btnNext_Background")
        self.lbl_background = QtWidgets.QLabel(self.centralwidget)
        self.lbl_background.setGeometry(QtCore.QRect(120, 50, 1024, 512))
        self.lbl_background.setObjectName("lbl_background")
        self.lbl_logo_1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_logo_1.setGeometry(QtCore.QRect(230, 250, 200, 200))
        self.lbl_logo_1.setObjectName("lbl_logo_1")
        self.lbl_logo_2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_logo_2.setGeometry(QtCore.QRect(870, 250, 200, 200))
        self.lbl_logo_2.setObjectName("lbl_logo_2")
        self.lbl_league = QtWidgets.QLabel(self.centralwidget)
        self.lbl_league.setGeometry(QtCore.QRect(130, 60, 151, 101))
        self.lbl_league.setObjectName("lbl_league")
        self.lbl_vs = QtWidgets.QLabel(self.centralwidget)
        self.lbl_vs.setGeometry(QtCore.QRect(590, 300, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_vs.setFont(font)
        self.lbl_vs.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_vs.setObjectName("lbl_vs")
        self.lbl_local = QtWidgets.QLabel(self.centralwidget)
        self.lbl_local.setGeometry(QtCore.QRect(450, 300, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_local.setFont(font)
        self.lbl_local.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_local.setObjectName("lbl_local")
        self.lbl_visitante = QtWidgets.QLabel(self.centralwidget)
        self.lbl_visitante.setGeometry(QtCore.QRect(730, 300, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_visitante.setFont(font)
        self.lbl_visitante.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_visitante.setObjectName("lbl_visitante")
        self.lbl_descripcion = QtWidgets.QLabel(self.centralwidget)
        self.lbl_descripcion.setGeometry(QtCore.QRect(360, 470, 601, 100))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_descripcion.setFont(font)
        self.lbl_descripcion.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_descripcion.setObjectName("lbl_descripcion")
        self.txt_local = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_local.setGeometry(QtCore.QRect(460, 710, 113, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_local.setFont(font)
        self.txt_local.setMaxLength(2)
        self.txt_local.setObjectName("txt_local")
        self.txt_visitante = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_visitante.setGeometry(QtCore.QRect(600, 710, 113, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_visitante.setFont(font)
        self.txt_visitante.setMaxLength(2)
        self.txt_visitante.setObjectName("txt_visitante")
        self.txt_descripcion = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_descripcion.setGeometry(QtCore.QRect(840, 710, 113, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_descripcion.setFont(font)
        self.txt_descripcion.setMaxLength(250)
        self.txt_descripcion.setObjectName("txt_descripcion")
        self.btnNext_League = QtWidgets.QPushButton(self.centralwidget)
        self.btnNext_League.setGeometry(QtCore.QRect(490, 650, 75, 23))
        self.btnNext_League.setObjectName("btnNext_League")
        self.btnNext_Logo = QtWidgets.QPushButton(self.centralwidget)
        self.btnNext_Logo.setGeometry(QtCore.QRect(260, 650, 101, 23))
        self.btnNext_Logo.setObjectName("btnNext_Logo")
        self.btnNext_Logo_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnNext_Logo_2.setGeometry(QtCore.QRect(370, 650, 111, 23))
        self.btnNext_Logo_2.setObjectName("btnNext_Logo_2")
        self.lbl_background.raise_()
        self.btnNext_Background.raise_()
        self.lbl_logo_1.raise_()
        self.lbl_logo_2.raise_()
        self.lbl_league.raise_()
        self.lbl_vs.raise_()
        self.lbl_local.raise_()
        self.lbl_visitante.raise_()
        self.lbl_descripcion.raise_()
        self.txt_local.raise_()
        self.txt_visitante.raise_()
        self.txt_descripcion.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConfiguration = QtWidgets.QAction(MainWindow)
        self.actionConfiguration.setObjectName("actionConfiguration")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionConfiguration)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UG Tweet Generator"))
        self.btnNext_Background.setText(_translate("MainWindow", "Next background"))
        self.lbl_background.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_logo_1.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_logo_2.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_league.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_vs.setText(_translate("MainWindow", "VS"))
        self.lbl_local.setText(_translate("MainWindow", "VS"))
        self.lbl_visitante.setText(_translate("MainWindow", "VS"))
        self.lbl_descripcion.setText(_translate("MainWindow", "VS"))
        self.btnNext_League.setText(_translate("MainWindow", "Next league"))
        self.btnNext_Logo.setText(_translate("MainWindow", "Next logo local"))
        self.btnNext_Logo_2.setText(_translate("MainWindow", "Next logo visitante"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionConfiguration.setText(_translate("MainWindow", "Configuration"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

