# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generator.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1043, 715)
        MainWindow.setMinimumSize(QtCore.QSize(1043, 715))
        MainWindow.setMaximumSize(QtCore.QSize(1043, 715))
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tbControls = QtWidgets.QTabWidget(self.centralwidget)
        self.tbControls.setGeometry(QtCore.QRect(10, 570, 1021, 101))
        self.tbControls.setAutoFillBackground(True)
        self.tbControls.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tbControls.setDocumentMode(False)
        self.tbControls.setTabBarAutoHide(True)
        self.tbControls.setObjectName("tbControls")
        self.tbLV = QtWidgets.QWidget()
        self.tbLV.setObjectName("tbLV")
        self.btnBackLocalLV = QtWidgets.QPushButton(self.tbLV)
        self.btnBackLocalLV.setGeometry(QtCore.QRect(100, 11, 31, 23))
        self.btnBackLocalLV.setObjectName("btnBackLocalLV")
        self.btnNextLocalLV = QtWidgets.QPushButton(self.tbLV)
        self.btnNextLocalLV.setGeometry(QtCore.QRect(210, 11, 31, 23))
        self.btnNextLocalLV.setObjectName("btnNextLocalLV")
        self.label = QtWidgets.QLabel(self.tbLV)
        self.label.setGeometry(QtCore.QRect(150, 13, 41, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tbLV)
        self.label_2.setGeometry(QtCore.QRect(770, 12, 71, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btnBackVisitorLV = QtWidgets.QPushButton(self.tbLV)
        self.btnBackVisitorLV.setGeometry(QtCore.QRect(730, 10, 31, 23))
        self.btnBackVisitorLV.setObjectName("btnBackVisitorLV")
        self.btnNextVisitorLV = QtWidgets.QPushButton(self.tbLV)
        self.btnNextVisitorLV.setGeometry(QtCore.QRect(840, 10, 31, 23))
        self.btnNextVisitorLV.setObjectName("btnNextVisitorLV")
        self.label_3 = QtWidgets.QLabel(self.tbLV)
        self.label_3.setGeometry(QtCore.QRect(460, 12, 81, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.txtResultLocalLV = QtWidgets.QLineEdit(self.tbLV)
        self.txtResultLocalLV.setGeometry(QtCore.QRect(420, 11, 31, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.txtResultLocalLV.setFont(font)
        self.txtResultLocalLV.setText("")
        self.txtResultLocalLV.setMaxLength(2)
        self.txtResultLocalLV.setAlignment(QtCore.Qt.AlignCenter)
        self.txtResultLocalLV.setObjectName("txtResultLocalLV")
        self.txtResultVisitorLV = QtWidgets.QLineEdit(self.tbLV)
        self.txtResultVisitorLV.setGeometry(QtCore.QRect(540, 10, 31, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.txtResultVisitorLV.setFont(font)
        self.txtResultVisitorLV.setText("")
        self.txtResultVisitorLV.setMaxLength(2)
        self.txtResultVisitorLV.setAlignment(QtCore.Qt.AlignCenter)
        self.txtResultVisitorLV.setObjectName("txtResultVisitorLV")
        self.txtMessageLV = QtWidgets.QLineEdit(self.tbLV)
        self.txtMessageLV.setGeometry(QtCore.QRect(212, 50, 551, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.txtMessageLV.setFont(font)
        self.txtMessageLV.setText("")
        self.txtMessageLV.setMaxLength(150)
        self.txtMessageLV.setClearButtonEnabled(False)
        self.txtMessageLV.setObjectName("txtMessageLV")
        self.tbControls.addTab(self.tbLV, "")
        self.tbAB = QtWidgets.QWidget()
        self.tbAB.setObjectName("tbAB")
        self.btnBackVisitorAB = QtWidgets.QPushButton(self.tbAB)
        self.btnBackVisitorAB.setGeometry(QtCore.QRect(730, 10, 31, 23))
        self.btnBackVisitorAB.setObjectName("btnBackVisitorAB")
        self.label_4 = QtWidgets.QLabel(self.tbAB)
        self.label_4.setGeometry(QtCore.QRect(140, 12, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txtResultLocalAB = QtWidgets.QLineEdit(self.tbAB)
        self.txtResultLocalAB.setGeometry(QtCore.QRect(420, 11, 31, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.txtResultLocalAB.setFont(font)
        self.txtResultLocalAB.setText("")
        self.txtResultLocalAB.setMaxLength(2)
        self.txtResultLocalAB.setAlignment(QtCore.Qt.AlignCenter)
        self.txtResultLocalAB.setObjectName("txtResultLocalAB")
        self.btnNextVisitorAB = QtWidgets.QPushButton(self.tbAB)
        self.btnNextVisitorAB.setGeometry(QtCore.QRect(840, 10, 31, 23))
        self.btnNextVisitorAB.setObjectName("btnNextVisitorAB")
        self.label_5 = QtWidgets.QLabel(self.tbAB)
        self.label_5.setGeometry(QtCore.QRect(460, 12, 81, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.txtResultVisitorAB = QtWidgets.QLineEdit(self.tbAB)
        self.txtResultVisitorAB.setGeometry(QtCore.QRect(540, 10, 31, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.txtResultVisitorAB.setFont(font)
        self.txtResultVisitorAB.setText("")
        self.txtResultVisitorAB.setMaxLength(2)
        self.txtResultVisitorAB.setAlignment(QtCore.Qt.AlignCenter)
        self.txtResultVisitorAB.setObjectName("txtResultVisitorAB")
        self.label_6 = QtWidgets.QLabel(self.tbAB)
        self.label_6.setGeometry(QtCore.QRect(770, 12, 71, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.txtMessageAB = QtWidgets.QLineEdit(self.tbAB)
        self.txtMessageAB.setGeometry(QtCore.QRect(212, 50, 551, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.txtMessageAB.setFont(font)
        self.txtMessageAB.setText("")
        self.txtMessageAB.setMaxLength(150)
        self.txtMessageAB.setClearButtonEnabled(False)
        self.txtMessageAB.setObjectName("txtMessageAB")
        self.btnBackLocalAB = QtWidgets.QPushButton(self.tbAB)
        self.btnBackLocalAB.setGeometry(QtCore.QRect(100, 11, 31, 23))
        self.btnBackLocalAB.setObjectName("btnBackLocalAB")
        self.btnNextLocalAB = QtWidgets.QPushButton(self.tbAB)
        self.btnNextLocalAB.setGeometry(QtCore.QRect(210, 11, 31, 23))
        self.btnNextLocalAB.setObjectName("btnNextLocalAB")
        self.tbControls.addTab(self.tbAB, "")
        self.tbP = QtWidgets.QWidget()
        self.tbP.setObjectName("tbP")
        self.label_7 = QtWidgets.QLabel(self.tbP)
        self.label_7.setGeometry(QtCore.QRect(200, 10, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.txt_driver = QtWidgets.QLineEdit(self.tbP)
        self.txt_driver.setGeometry(QtCore.QRect(200, 30, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.txt_driver.setFont(font)
        self.txt_driver.setObjectName("txt_driver")
        self.txt_car = QtWidgets.QLineEdit(self.tbP)
        self.txt_car.setGeometry(QtCore.QRect(350, 30, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.txt_car.setFont(font)
        self.txt_car.setObjectName("txt_car")
        self.txt_position = QtWidgets.QLineEdit(self.tbP)
        self.txt_position.setGeometry(QtCore.QRect(650, 30, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.txt_position.setFont(font)
        self.txt_position.setMaxLength(2)
        self.txt_position.setObjectName("txt_position")
        self.txtCoche = QtWidgets.QLabel(self.tbP)
        self.txtCoche.setGeometry(QtCore.QRect(350, 10, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.txtCoche.setFont(font)
        self.txtCoche.setObjectName("txtCoche")
        self.label_9 = QtWidgets.QLabel(self.tbP)
        self.label_9.setGeometry(QtCore.QRect(650, 10, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.txt_track = QtWidgets.QLineEdit(self.tbP)
        self.txt_track.setGeometry(QtCore.QRect(500, 30, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.txt_track.setFont(font)
        self.txt_track.setObjectName("txt_track")
        self.label_10 = QtWidgets.QLabel(self.tbP)
        self.label_10.setGeometry(QtCore.QRect(500, 10, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.tbControls.addTab(self.tbP, "")
        self.tbPanel = QtWidgets.QTabWidget(self.centralwidget)
        self.tbPanel.setGeometry(QtCore.QRect(10, 0, 1021, 561))
        self.tbPanel.setAutoFillBackground(True)
        self.tbPanel.setStyleSheet("")
        self.tbPanel.setTabBarAutoHide(True)
        self.tbPanel.setObjectName("tbPanel")
        self.tbResult = QtWidgets.QWidget()
        self.tbResult.setObjectName("tbResult")
        self.btnChange_Competition = QtWidgets.QPushButton(self.tbResult)
        self.btnChange_Competition.setGeometry(QtCore.QRect(0, 0, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btnChange_Competition.setFont(font)
        self.btnChange_Competition.setObjectName("btnChange_Competition")
        self.btnChange_Background = QtWidgets.QPushButton(self.tbResult)
        self.btnChange_Background.setGeometry(QtCore.QRect(160, 0, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btnChange_Background.setFont(font)
        self.btnChange_Background.setObjectName("btnChange_Background")
        self.lbl_competition = QtWidgets.QLabel(self.tbResult)
        self.lbl_competition.setGeometry(QtCore.QRect(10, 50, 80, 80))
        self.lbl_competition.setObjectName("lbl_competition")
        self.lbl_visitor = QtWidgets.QLabel(self.tbResult)
        self.lbl_visitor.setGeometry(QtCore.QRect(540, 230, 120, 100))
        font = QtGui.QFont()
        font.setFamily("Unica One")
        font.setPointSize(70)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_visitor.setFont(font)
        self.lbl_visitor.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_visitor.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_visitor.setObjectName("lbl_visitor")
        self.lbl_logo_team_b = QtWidgets.QLabel(self.tbResult)
        self.lbl_logo_team_b.setGeometry(QtCore.QRect(710, 190, 200, 200))
        self.lbl_logo_team_b.setObjectName("lbl_logo_team_b")
        self.lbl_background = QtWidgets.QLabel(self.tbResult)
        self.lbl_background.setGeometry(QtCore.QRect(0, 40, 1011, 491))
        self.lbl_background.setObjectName("lbl_background")
        self.lbl_logo_team_a = QtWidgets.QLabel(self.tbResult)
        self.lbl_logo_team_a.setGeometry(QtCore.QRect(80, 190, 200, 200))
        self.lbl_logo_team_a.setObjectName("lbl_logo_team_a")
        self.lbl_local = QtWidgets.QLabel(self.tbResult)
        self.lbl_local.setGeometry(QtCore.QRect(330, 230, 120, 100))
        font = QtGui.QFont()
        font.setFamily("Unica One")
        font.setPointSize(70)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_local.setFont(font)
        self.lbl_local.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_local.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_local.setObjectName("lbl_local")
        self.lbl_vs = QtWidgets.QLabel(self.tbResult)
        self.lbl_vs.setGeometry(QtCore.QRect(460, 250, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Unica One")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_vs.setFont(font)
        self.lbl_vs.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_vs.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_vs.setObjectName("lbl_vs")
        self.lbl_description = QtWidgets.QLabel(self.tbResult)
        self.lbl_description.setGeometry(QtCore.QRect(10, 450, 991, 100))
        font = QtGui.QFont()
        font.setFamily("Unica One")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_description.setFont(font)
        self.lbl_description.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_description.setText("")
        self.lbl_description.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_description.setObjectName("lbl_description")
        self.btn_save_image_r = QtWidgets.QPushButton(self.tbResult)
        self.btn_save_image_r.setGeometry(QtCore.QRect(320, 0, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_save_image_r.setFont(font)
        self.btn_save_image_r.setObjectName("btn_save_image_r")
        self.btnChange_Competition.raise_()
        self.btnChange_Background.raise_()
        self.lbl_background.raise_()
        self.lbl_logo_team_a.raise_()
        self.lbl_local.raise_()
        self.lbl_logo_team_b.raise_()
        self.lbl_visitor.raise_()
        self.lbl_vs.raise_()
        self.lbl_description.raise_()
        self.lbl_competition.raise_()
        self.btn_save_image_r.raise_()
        self.tbPanel.addTab(self.tbResult, "")
        self.tbPosition = QtWidgets.QWidget()
        self.tbPosition.setObjectName("tbPosition")
        self.lbl_background_panel_p = QtWidgets.QLabel(self.tbPosition)
        self.lbl_background_panel_p.setGeometry(QtCore.QRect(0, 41, 1011, 491))
        self.lbl_background_panel_p.setText("")
        self.lbl_background_panel_p.setObjectName("lbl_background_panel_p")
        self.lbl_driver = QtWidgets.QLabel(self.tbPosition)
        self.lbl_driver.setGeometry(QtCore.QRect(60, 180, 651, 71))
        font = QtGui.QFont()
        font.setFamily("Unica One")
        font.setPointSize(40)
        self.lbl_driver.setFont(font)
        self.lbl_driver.setStyleSheet("color:rgb(255,255,255);")
        self.lbl_driver.setText("")
        self.lbl_driver.setObjectName("lbl_driver")
        self.lbl_car = QtWidgets.QLabel(self.tbPosition)
        self.lbl_car.setGeometry(QtCore.QRect(60, 250, 591, 71))
        font = QtGui.QFont()
        font.setFamily("Unica One")
        font.setPointSize(40)
        self.lbl_car.setFont(font)
        self.lbl_car.setStyleSheet("color:rgb(255,255,255);")
        self.lbl_car.setText("")
        self.lbl_car.setObjectName("lbl_car")
        self.lbl_track = QtWidgets.QLabel(self.tbPosition)
        self.lbl_track.setGeometry(QtCore.QRect(60, 320, 591, 131))
        font = QtGui.QFont()
        font.setFamily("Unica One")
        font.setPointSize(40)
        self.lbl_track.setFont(font)
        self.lbl_track.setStyleSheet("color:rgb(255,255,255);")
        self.lbl_track.setText("")
        self.lbl_track.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_track.setWordWrap(True)
        self.lbl_track.setObjectName("lbl_track")
        self.lbl_position = QtWidgets.QLabel(self.tbPosition)
        self.lbl_position.setGeometry(QtCore.QRect(700, 180, 261, 191))
        font = QtGui.QFont()
        font.setFamily("Unica One")
        font.setPointSize(200)
        self.lbl_position.setFont(font)
        self.lbl_position.setStyleSheet("color:rgb(255,255,255);")
        self.lbl_position.setText("")
        self.lbl_position.setObjectName("lbl_position")
        self.btn_change_background_p = QtWidgets.QPushButton(self.tbPosition)
        self.btn_change_background_p.setGeometry(QtCore.QRect(0, 0, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_change_background_p.setFont(font)
        self.btn_change_background_p.setObjectName("btn_change_background_p")
        self.btn_save_image_p = QtWidgets.QPushButton(self.tbPosition)
        self.btn_save_image_p.setGeometry(QtCore.QRect(150, 0, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_save_image_p.setFont(font)
        self.btn_save_image_p.setObjectName("btn_save_image_p")
        self.lbl_position_2 = QtWidgets.QLabel(self.tbPosition)
        self.lbl_position_2.setGeometry(QtCore.QRect(650, 280, 71, 91))
        font = QtGui.QFont()
        font.setFamily("Unica One")
        font.setPointSize(80)
        self.lbl_position_2.setFont(font)
        self.lbl_position_2.setStyleSheet("color:rgb(255,255,255);")
        self.lbl_position_2.setObjectName("lbl_position_2")
        self.tbPanel.addTab(self.tbPosition, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1043, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHerramientas = QtWidgets.QMenu(self.menubar)
        self.menuHerramientas.setObjectName("menuHerramientas")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConfiguration = QtWidgets.QAction(MainWindow)
        self.actionConfiguration.setObjectName("actionConfiguration")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.action_UpdateImageLibrary = QtWidgets.QAction(MainWindow)
        self.action_UpdateImageLibrary.setObjectName("action_UpdateImageLibrary")
        self.menuFile.addAction(self.actionConfiguration)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHerramientas.addAction(self.action_UpdateImageLibrary)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHerramientas.menuAction())

        self.retranslateUi(MainWindow)
        self.tbControls.setCurrentIndex(2)
        self.tbPanel.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btnChange_Competition, self.btnChange_Background)
        MainWindow.setTabOrder(self.btnChange_Background, self.btnBackLocalLV)
        MainWindow.setTabOrder(self.btnBackLocalLV, self.btnNextLocalLV)
        MainWindow.setTabOrder(self.btnNextLocalLV, self.txtResultLocalLV)
        MainWindow.setTabOrder(self.txtResultLocalLV, self.txtResultVisitorLV)
        MainWindow.setTabOrder(self.txtResultVisitorLV, self.btnBackVisitorLV)
        MainWindow.setTabOrder(self.btnBackVisitorLV, self.btnNextVisitorLV)
        MainWindow.setTabOrder(self.btnNextVisitorLV, self.txtMessageLV)
        MainWindow.setTabOrder(self.txtMessageLV, self.btnBackLocalAB)
        MainWindow.setTabOrder(self.btnBackLocalAB, self.btnNextLocalAB)
        MainWindow.setTabOrder(self.btnNextLocalAB, self.txtResultLocalAB)
        MainWindow.setTabOrder(self.txtResultLocalAB, self.txtResultVisitorAB)
        MainWindow.setTabOrder(self.txtResultVisitorAB, self.btnBackVisitorAB)
        MainWindow.setTabOrder(self.btnBackVisitorAB, self.btnNextVisitorAB)
        MainWindow.setTabOrder(self.btnNextVisitorAB, self.txtMessageAB)
        MainWindow.setTabOrder(self.txtMessageAB, self.txt_driver)
        MainWindow.setTabOrder(self.txt_driver, self.txt_car)
        MainWindow.setTabOrder(self.txt_car, self.txt_track)
        MainWindow.setTabOrder(self.txt_track, self.txt_position)
        MainWindow.setTabOrder(self.txt_position, self.btn_change_background_p)
        MainWindow.setTabOrder(self.btn_change_background_p, self.tbControls)
        MainWindow.setTabOrder(self.tbControls, self.tbPanel)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UG Tweet Generator"))
        self.btnBackLocalLV.setText(_translate("MainWindow", "<<"))
        self.btnNextLocalLV.setText(_translate("MainWindow", ">>"))
        self.label.setText(_translate("MainWindow", "LOCAL"))
        self.label_2.setText(_translate("MainWindow", "VISITANTE"))
        self.btnBackVisitorLV.setText(_translate("MainWindow", "<<"))
        self.btnNextVisitorLV.setText(_translate("MainWindow", ">>"))
        self.label_3.setText(_translate("MainWindow", "RESULTADO"))
        self.txtMessageLV.setPlaceholderText(_translate("MainWindow", "Escribe el mensaje que aparecerá en la imágen"))
        self.tbControls.setTabText(self.tbControls.indexOf(self.tbLV), _translate("MainWindow", "L - V"))
        self.btnBackVisitorAB.setText(_translate("MainWindow", "<<"))
        self.label_4.setText(_translate("MainWindow", "Equipo A"))
        self.btnNextVisitorAB.setText(_translate("MainWindow", ">>"))
        self.label_5.setText(_translate("MainWindow", "RESULTADO"))
        self.label_6.setText(_translate("MainWindow", "Equipo B"))
        self.txtMessageAB.setPlaceholderText(_translate("MainWindow", "Escribe el mensaje que aparecerá en la imágen"))
        self.btnBackLocalAB.setText(_translate("MainWindow", "<<"))
        self.btnNextLocalAB.setText(_translate("MainWindow", ">>"))
        self.tbControls.setTabText(self.tbControls.indexOf(self.tbAB), _translate("MainWindow", "A - B"))
        self.label_7.setText(_translate("MainWindow", "Piloto"))
        self.txtCoche.setText(_translate("MainWindow", "Coche"))
        self.label_9.setText(_translate("MainWindow", "Posición"))
        self.label_10.setText(_translate("MainWindow", "Circuito"))
        self.tbControls.setTabText(self.tbControls.indexOf(self.tbP), _translate("MainWindow", "P"))
        self.btnChange_Competition.setText(_translate("MainWindow", "Cambiar competición"))
        self.btnChange_Background.setText(_translate("MainWindow", "Cambiar fondo"))
        self.lbl_competition.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_visitor.setText(_translate("MainWindow", "0"))
        self.lbl_logo_team_b.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_background.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_logo_team_a.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_local.setText(_translate("MainWindow", "0"))
        self.lbl_vs.setText(_translate("MainWindow", "VS"))
        self.btn_save_image_r.setText(_translate("MainWindow", "Guardar imágen"))
        self.tbPanel.setTabText(self.tbPanel.indexOf(self.tbResult), _translate("MainWindow", "T - R"))
        self.btn_change_background_p.setText(_translate("MainWindow", "Cambiar fondo"))
        self.btn_save_image_p.setText(_translate("MainWindow", "Guardar imágen"))
        self.lbl_position_2.setText(_translate("MainWindow", "#"))
        self.tbPanel.setTabText(self.tbPanel.indexOf(self.tbPosition), _translate("MainWindow", "T - P"))
        self.menuFile.setTitle(_translate("MainWindow", "Archivo"))
        self.menuHerramientas.setTitle(_translate("MainWindow", "Herramientas"))
        self.actionConfiguration.setText(_translate("MainWindow", "Configuration"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.action_UpdateImageLibrary.setText(_translate("MainWindow", "Actualizar biblioteca de imágenes"))
